name: Automatic Data Preprocessing

# Trigger workflow ini pada setiap push ke branch 'main'
# atau pada pull request yang menargetkan branch 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preprocess-data:
    runs-on: ubuntu-latest # Menggunakan runner Linux terbaru yang disediakan GitHub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Mengunduh kode dari repository Anda ke runner

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn
        # Tambahkan library lain jika skrip Anda membutuhkannya

    - name: Run data preprocessing script
      run: |
        cd preprocessing  # Pindah ke direktori tempat skrip berada
        python automate_Mochammad-Rafly-Herdianto.py
      # Skrip akan membaca dari '../supplement_sales_raw.csv'
      # dan menyimpan hasilnya ke 'supplement_sales_preprocessing.csv' di dalam folder 'preprocessing'

    - name: Upload preprocessed data artifact
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-supplement-sales # Nama artifak yang akan diunggah
        path: preprocessing/supplement_sales_preprocessing.csv # Path ke file yang akan diunggah
        if-no-files-found: error # Gagal jika file tidak ditemukan